-- Generated by scripts/migrate-uploads-to-cloudinary.ps1
-- Run this against the Railway PostgreSQL database after reviewing it.
-- Source folder: E:\SCHOOLS\Thuong_mai_dien_tu\E-commerce-LUMOS-AURA\BE\uploads
-- Cloudinary folder: Products
BEGIN;

-- 005b2c7d-99b0-4dce-9f14-6975b19f35db.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639439/Products/005b2c7d-99b0-4dce-9f14-6975b19f35db.png'
WHERE image_url LIKE '%/uploads/005b2c7d-99b0-4dce-9f14-6975b19f35db.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639439/Products/005b2c7d-99b0-4dce-9f14-6975b19f35db.png'
WHERE thumbnail_url LIKE '%/uploads/005b2c7d-99b0-4dce-9f14-6975b19f35db.png';

-- 050b2f49-59a3-4ce0-84fe-5836b9dc955b.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639445/Products/050b2f49-59a3-4ce0-84fe-5836b9dc955b.png'
WHERE image_url LIKE '%/uploads/050b2f49-59a3-4ce0-84fe-5836b9dc955b.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639445/Products/050b2f49-59a3-4ce0-84fe-5836b9dc955b.png'
WHERE thumbnail_url LIKE '%/uploads/050b2f49-59a3-4ce0-84fe-5836b9dc955b.png';

-- 07d07582-a4b8-4e26-9b0a-0185928c860b.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639451/Products/07d07582-a4b8-4e26-9b0a-0185928c860b.png'
WHERE image_url LIKE '%/uploads/07d07582-a4b8-4e26-9b0a-0185928c860b.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639451/Products/07d07582-a4b8-4e26-9b0a-0185928c860b.png'
WHERE thumbnail_url LIKE '%/uploads/07d07582-a4b8-4e26-9b0a-0185928c860b.png';

-- 0ba8cf43-4498-443f-bfcd-0e16e52d9341.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639827/Products/0ba8cf43-4498-443f-bfcd-0e16e52d9341.png'
WHERE image_url LIKE '%/uploads/0ba8cf43-4498-443f-bfcd-0e16e52d9341.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639827/Products/0ba8cf43-4498-443f-bfcd-0e16e52d9341.png'
WHERE thumbnail_url LIKE '%/uploads/0ba8cf43-4498-443f-bfcd-0e16e52d9341.png';

-- 0c7b4486-1fb7-4ccc-8900-e5cb7fb2c8fb.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639834/Products/0c7b4486-1fb7-4ccc-8900-e5cb7fb2c8fb.png'
WHERE image_url LIKE '%/uploads/0c7b4486-1fb7-4ccc-8900-e5cb7fb2c8fb.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639834/Products/0c7b4486-1fb7-4ccc-8900-e5cb7fb2c8fb.png'
WHERE thumbnail_url LIKE '%/uploads/0c7b4486-1fb7-4ccc-8900-e5cb7fb2c8fb.png';

-- 0fcb1d05-76ce-406a-8314-99debf66e10d.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639840/Products/0fcb1d05-76ce-406a-8314-99debf66e10d.png'
WHERE image_url LIKE '%/uploads/0fcb1d05-76ce-406a-8314-99debf66e10d.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639840/Products/0fcb1d05-76ce-406a-8314-99debf66e10d.png'
WHERE thumbnail_url LIKE '%/uploads/0fcb1d05-76ce-406a-8314-99debf66e10d.png';

-- 10c22b37-692d-4ba5-9f30-6c63a0ba38d2.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639848/Products/10c22b37-692d-4ba5-9f30-6c63a0ba38d2.png'
WHERE image_url LIKE '%/uploads/10c22b37-692d-4ba5-9f30-6c63a0ba38d2.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639848/Products/10c22b37-692d-4ba5-9f30-6c63a0ba38d2.png'
WHERE thumbnail_url LIKE '%/uploads/10c22b37-692d-4ba5-9f30-6c63a0ba38d2.png';

-- 230b9b4f-ac8f-4b0a-a60c-b3a0e7b3ec89.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639855/Products/230b9b4f-ac8f-4b0a-a60c-b3a0e7b3ec89.png'
WHERE image_url LIKE '%/uploads/230b9b4f-ac8f-4b0a-a60c-b3a0e7b3ec89.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639855/Products/230b9b4f-ac8f-4b0a-a60c-b3a0e7b3ec89.png'
WHERE thumbnail_url LIKE '%/uploads/230b9b4f-ac8f-4b0a-a60c-b3a0e7b3ec89.png';

-- 247bce86-19cf-4c2d-954d-719cbe1ad292.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639866/Products/247bce86-19cf-4c2d-954d-719cbe1ad292.png'
WHERE image_url LIKE '%/uploads/247bce86-19cf-4c2d-954d-719cbe1ad292.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639866/Products/247bce86-19cf-4c2d-954d-719cbe1ad292.png'
WHERE thumbnail_url LIKE '%/uploads/247bce86-19cf-4c2d-954d-719cbe1ad292.png';

-- 2a1f8000-80ee-4b71-bf31-a8125ccd75cc.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639876/Products/2a1f8000-80ee-4b71-bf31-a8125ccd75cc.png'
WHERE image_url LIKE '%/uploads/2a1f8000-80ee-4b71-bf31-a8125ccd75cc.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639876/Products/2a1f8000-80ee-4b71-bf31-a8125ccd75cc.png'
WHERE thumbnail_url LIKE '%/uploads/2a1f8000-80ee-4b71-bf31-a8125ccd75cc.png';

-- 2bcf52cb-1a1b-4380-af0a-6076cb45594a.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639884/Products/2bcf52cb-1a1b-4380-af0a-6076cb45594a.png'
WHERE image_url LIKE '%/uploads/2bcf52cb-1a1b-4380-af0a-6076cb45594a.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639884/Products/2bcf52cb-1a1b-4380-af0a-6076cb45594a.png'
WHERE thumbnail_url LIKE '%/uploads/2bcf52cb-1a1b-4380-af0a-6076cb45594a.png';

-- 2bd83b8a-c6fe-4c37-9986-f8de33371a11.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639891/Products/2bd83b8a-c6fe-4c37-9986-f8de33371a11.png'
WHERE image_url LIKE '%/uploads/2bd83b8a-c6fe-4c37-9986-f8de33371a11.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639891/Products/2bd83b8a-c6fe-4c37-9986-f8de33371a11.png'
WHERE thumbnail_url LIKE '%/uploads/2bd83b8a-c6fe-4c37-9986-f8de33371a11.png';

-- 2dc4799a-afc4-472e-b398-d86adc9aa47f.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639899/Products/2dc4799a-afc4-472e-b398-d86adc9aa47f.png'
WHERE image_url LIKE '%/uploads/2dc4799a-afc4-472e-b398-d86adc9aa47f.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639899/Products/2dc4799a-afc4-472e-b398-d86adc9aa47f.png'
WHERE thumbnail_url LIKE '%/uploads/2dc4799a-afc4-472e-b398-d86adc9aa47f.png';

-- 30fd0322-9644-473d-9bd4-28132cd6b8a0.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639907/Products/30fd0322-9644-473d-9bd4-28132cd6b8a0.png'
WHERE image_url LIKE '%/uploads/30fd0322-9644-473d-9bd4-28132cd6b8a0.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639907/Products/30fd0322-9644-473d-9bd4-28132cd6b8a0.png'
WHERE thumbnail_url LIKE '%/uploads/30fd0322-9644-473d-9bd4-28132cd6b8a0.png';

-- 34c0739d-e0ea-4110-a9dc-7d561c5fcee6.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639914/Products/34c0739d-e0ea-4110-a9dc-7d561c5fcee6.png'
WHERE image_url LIKE '%/uploads/34c0739d-e0ea-4110-a9dc-7d561c5fcee6.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639914/Products/34c0739d-e0ea-4110-a9dc-7d561c5fcee6.png'
WHERE thumbnail_url LIKE '%/uploads/34c0739d-e0ea-4110-a9dc-7d561c5fcee6.png';

-- 3c74c57d-8721-4520-a0b1-15540f4d3157.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639923/Products/3c74c57d-8721-4520-a0b1-15540f4d3157.png'
WHERE image_url LIKE '%/uploads/3c74c57d-8721-4520-a0b1-15540f4d3157.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639923/Products/3c74c57d-8721-4520-a0b1-15540f4d3157.png'
WHERE thumbnail_url LIKE '%/uploads/3c74c57d-8721-4520-a0b1-15540f4d3157.png';

-- 3d429b00-d602-4df4-a0b8-ba1fe4c0e6b9.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639930/Products/3d429b00-d602-4df4-a0b8-ba1fe4c0e6b9.png'
WHERE image_url LIKE '%/uploads/3d429b00-d602-4df4-a0b8-ba1fe4c0e6b9.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639930/Products/3d429b00-d602-4df4-a0b8-ba1fe4c0e6b9.png'
WHERE thumbnail_url LIKE '%/uploads/3d429b00-d602-4df4-a0b8-ba1fe4c0e6b9.png';

-- 40db78f2-4101-4980-b547-eb70e555dfa6.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639938/Products/40db78f2-4101-4980-b547-eb70e555dfa6.png'
WHERE image_url LIKE '%/uploads/40db78f2-4101-4980-b547-eb70e555dfa6.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639938/Products/40db78f2-4101-4980-b547-eb70e555dfa6.png'
WHERE thumbnail_url LIKE '%/uploads/40db78f2-4101-4980-b547-eb70e555dfa6.png';

-- 42afb093-7090-4939-82e9-2567943c34d8.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639947/Products/42afb093-7090-4939-82e9-2567943c34d8.png'
WHERE image_url LIKE '%/uploads/42afb093-7090-4939-82e9-2567943c34d8.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639947/Products/42afb093-7090-4939-82e9-2567943c34d8.png'
WHERE thumbnail_url LIKE '%/uploads/42afb093-7090-4939-82e9-2567943c34d8.png';

-- 45639ec7-5133-4679-bc1b-4e7070579c82.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639953/Products/45639ec7-5133-4679-bc1b-4e7070579c82.png'
WHERE image_url LIKE '%/uploads/45639ec7-5133-4679-bc1b-4e7070579c82.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639953/Products/45639ec7-5133-4679-bc1b-4e7070579c82.png'
WHERE thumbnail_url LIKE '%/uploads/45639ec7-5133-4679-bc1b-4e7070579c82.png';

-- 474ae432-bb81-4c2d-afd4-864cdab032a3.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639959/Products/474ae432-bb81-4c2d-afd4-864cdab032a3.png'
WHERE image_url LIKE '%/uploads/474ae432-bb81-4c2d-afd4-864cdab032a3.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639959/Products/474ae432-bb81-4c2d-afd4-864cdab032a3.png'
WHERE thumbnail_url LIKE '%/uploads/474ae432-bb81-4c2d-afd4-864cdab032a3.png';

-- 48cb012d-6728-4a38-9077-79ec75b93a96.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639965/Products/48cb012d-6728-4a38-9077-79ec75b93a96.png'
WHERE image_url LIKE '%/uploads/48cb012d-6728-4a38-9077-79ec75b93a96.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639965/Products/48cb012d-6728-4a38-9077-79ec75b93a96.png'
WHERE thumbnail_url LIKE '%/uploads/48cb012d-6728-4a38-9077-79ec75b93a96.png';

-- 4e9ff36f-fafd-42dd-8ede-f315c5dc175c.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639970/Products/4e9ff36f-fafd-42dd-8ede-f315c5dc175c.png'
WHERE image_url LIKE '%/uploads/4e9ff36f-fafd-42dd-8ede-f315c5dc175c.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639970/Products/4e9ff36f-fafd-42dd-8ede-f315c5dc175c.png'
WHERE thumbnail_url LIKE '%/uploads/4e9ff36f-fafd-42dd-8ede-f315c5dc175c.png';

-- 4eadd858-e8c5-4ed4-817e-98bcfdcce7d5.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639977/Products/4eadd858-e8c5-4ed4-817e-98bcfdcce7d5.png'
WHERE image_url LIKE '%/uploads/4eadd858-e8c5-4ed4-817e-98bcfdcce7d5.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639977/Products/4eadd858-e8c5-4ed4-817e-98bcfdcce7d5.png'
WHERE thumbnail_url LIKE '%/uploads/4eadd858-e8c5-4ed4-817e-98bcfdcce7d5.png';

-- 4f4e7117-1a34-4fc8-9dfe-74525b8bb949.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639986/Products/4f4e7117-1a34-4fc8-9dfe-74525b8bb949.png'
WHERE image_url LIKE '%/uploads/4f4e7117-1a34-4fc8-9dfe-74525b8bb949.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639986/Products/4f4e7117-1a34-4fc8-9dfe-74525b8bb949.png'
WHERE thumbnail_url LIKE '%/uploads/4f4e7117-1a34-4fc8-9dfe-74525b8bb949.png';

-- 5270be93-a63e-4e2a-944f-2b714d06f6b4.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639993/Products/5270be93-a63e-4e2a-944f-2b714d06f6b4.png'
WHERE image_url LIKE '%/uploads/5270be93-a63e-4e2a-944f-2b714d06f6b4.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782639993/Products/5270be93-a63e-4e2a-944f-2b714d06f6b4.png'
WHERE thumbnail_url LIKE '%/uploads/5270be93-a63e-4e2a-944f-2b714d06f6b4.png';

-- 56c345ca-a641-455b-8630-1609777b11a3.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640001/Products/56c345ca-a641-455b-8630-1609777b11a3.png'
WHERE image_url LIKE '%/uploads/56c345ca-a641-455b-8630-1609777b11a3.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640001/Products/56c345ca-a641-455b-8630-1609777b11a3.png'
WHERE thumbnail_url LIKE '%/uploads/56c345ca-a641-455b-8630-1609777b11a3.png';

-- 56d42d80-39ef-4dbd-a308-3758acb82013.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640009/Products/56d42d80-39ef-4dbd-a308-3758acb82013.png'
WHERE image_url LIKE '%/uploads/56d42d80-39ef-4dbd-a308-3758acb82013.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640009/Products/56d42d80-39ef-4dbd-a308-3758acb82013.png'
WHERE thumbnail_url LIKE '%/uploads/56d42d80-39ef-4dbd-a308-3758acb82013.png';

-- 57ba02b9-9e9a-4515-ba53-5b78c7d1cff3.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640016/Products/57ba02b9-9e9a-4515-ba53-5b78c7d1cff3.png'
WHERE image_url LIKE '%/uploads/57ba02b9-9e9a-4515-ba53-5b78c7d1cff3.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640016/Products/57ba02b9-9e9a-4515-ba53-5b78c7d1cff3.png'
WHERE thumbnail_url LIKE '%/uploads/57ba02b9-9e9a-4515-ba53-5b78c7d1cff3.png';

-- 5ac30f6e-dcec-49d4-b4ed-f8242d7f0db0.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640022/Products/5ac30f6e-dcec-49d4-b4ed-f8242d7f0db0.png'
WHERE image_url LIKE '%/uploads/5ac30f6e-dcec-49d4-b4ed-f8242d7f0db0.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640022/Products/5ac30f6e-dcec-49d4-b4ed-f8242d7f0db0.png'
WHERE thumbnail_url LIKE '%/uploads/5ac30f6e-dcec-49d4-b4ed-f8242d7f0db0.png';

-- 5b7e9e49-0d85-4431-aa41-d14b24bdbfe4.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640028/Products/5b7e9e49-0d85-4431-aa41-d14b24bdbfe4.png'
WHERE image_url LIKE '%/uploads/5b7e9e49-0d85-4431-aa41-d14b24bdbfe4.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640028/Products/5b7e9e49-0d85-4431-aa41-d14b24bdbfe4.png'
WHERE thumbnail_url LIKE '%/uploads/5b7e9e49-0d85-4431-aa41-d14b24bdbfe4.png';

-- 5e946055-2704-4a90-8669-05c2e5ec6130.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640040/Products/5e946055-2704-4a90-8669-05c2e5ec6130.png'
WHERE image_url LIKE '%/uploads/5e946055-2704-4a90-8669-05c2e5ec6130.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640040/Products/5e946055-2704-4a90-8669-05c2e5ec6130.png'
WHERE thumbnail_url LIKE '%/uploads/5e946055-2704-4a90-8669-05c2e5ec6130.png';

-- 6656e8e2-b802-4c4c-a9ff-7eff6c2b916d.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640046/Products/6656e8e2-b802-4c4c-a9ff-7eff6c2b916d.png'
WHERE image_url LIKE '%/uploads/6656e8e2-b802-4c4c-a9ff-7eff6c2b916d.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640046/Products/6656e8e2-b802-4c4c-a9ff-7eff6c2b916d.png'
WHERE thumbnail_url LIKE '%/uploads/6656e8e2-b802-4c4c-a9ff-7eff6c2b916d.png';

-- 66ccb028-b735-4594-b94f-4a14a0794929.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640052/Products/66ccb028-b735-4594-b94f-4a14a0794929.png'
WHERE image_url LIKE '%/uploads/66ccb028-b735-4594-b94f-4a14a0794929.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640052/Products/66ccb028-b735-4594-b94f-4a14a0794929.png'
WHERE thumbnail_url LIKE '%/uploads/66ccb028-b735-4594-b94f-4a14a0794929.png';

-- 6d269f3c-6dcb-4a82-b9a1-5fc6b75dee7e.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640059/Products/6d269f3c-6dcb-4a82-b9a1-5fc6b75dee7e.png'
WHERE image_url LIKE '%/uploads/6d269f3c-6dcb-4a82-b9a1-5fc6b75dee7e.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640059/Products/6d269f3c-6dcb-4a82-b9a1-5fc6b75dee7e.png'
WHERE thumbnail_url LIKE '%/uploads/6d269f3c-6dcb-4a82-b9a1-5fc6b75dee7e.png';

-- 6f72c58d-445b-4921-a1ba-fc74106f6608.jpg
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640066/Products/6f72c58d-445b-4921-a1ba-fc74106f6608.png'
WHERE image_url LIKE '%/uploads/6f72c58d-445b-4921-a1ba-fc74106f6608.jpg';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640066/Products/6f72c58d-445b-4921-a1ba-fc74106f6608.png'
WHERE thumbnail_url LIKE '%/uploads/6f72c58d-445b-4921-a1ba-fc74106f6608.jpg';

-- 725ec98c-847f-48da-90ee-ad2e63ac1b4c.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640072/Products/725ec98c-847f-48da-90ee-ad2e63ac1b4c.png'
WHERE image_url LIKE '%/uploads/725ec98c-847f-48da-90ee-ad2e63ac1b4c.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640072/Products/725ec98c-847f-48da-90ee-ad2e63ac1b4c.png'
WHERE thumbnail_url LIKE '%/uploads/725ec98c-847f-48da-90ee-ad2e63ac1b4c.png';

-- 728efea7-a0b2-4c9c-a47d-70c1084161fc.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640078/Products/728efea7-a0b2-4c9c-a47d-70c1084161fc.png'
WHERE image_url LIKE '%/uploads/728efea7-a0b2-4c9c-a47d-70c1084161fc.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640078/Products/728efea7-a0b2-4c9c-a47d-70c1084161fc.png'
WHERE thumbnail_url LIKE '%/uploads/728efea7-a0b2-4c9c-a47d-70c1084161fc.png';

-- 740afac5-4fa1-44cb-820f-af969a35ef80.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640086/Products/740afac5-4fa1-44cb-820f-af969a35ef80.png'
WHERE image_url LIKE '%/uploads/740afac5-4fa1-44cb-820f-af969a35ef80.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640086/Products/740afac5-4fa1-44cb-820f-af969a35ef80.png'
WHERE thumbnail_url LIKE '%/uploads/740afac5-4fa1-44cb-820f-af969a35ef80.png';

-- 783448e4-a307-4dcb-b6c5-f95c96ca0de2.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640093/Products/783448e4-a307-4dcb-b6c5-f95c96ca0de2.png'
WHERE image_url LIKE '%/uploads/783448e4-a307-4dcb-b6c5-f95c96ca0de2.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640093/Products/783448e4-a307-4dcb-b6c5-f95c96ca0de2.png'
WHERE thumbnail_url LIKE '%/uploads/783448e4-a307-4dcb-b6c5-f95c96ca0de2.png';

-- 828e4894-8265-47e5-bd59-931c87c10207.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640099/Products/828e4894-8265-47e5-bd59-931c87c10207.png'
WHERE image_url LIKE '%/uploads/828e4894-8265-47e5-bd59-931c87c10207.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640099/Products/828e4894-8265-47e5-bd59-931c87c10207.png'
WHERE thumbnail_url LIKE '%/uploads/828e4894-8265-47e5-bd59-931c87c10207.png';

-- 88f3e18b-c540-4d1b-8544-8ab57aed5a12.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640106/Products/88f3e18b-c540-4d1b-8544-8ab57aed5a12.png'
WHERE image_url LIKE '%/uploads/88f3e18b-c540-4d1b-8544-8ab57aed5a12.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640106/Products/88f3e18b-c540-4d1b-8544-8ab57aed5a12.png'
WHERE thumbnail_url LIKE '%/uploads/88f3e18b-c540-4d1b-8544-8ab57aed5a12.png';

-- 8f70f7ca-dcb1-4509-b38c-dd327728045c.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640113/Products/8f70f7ca-dcb1-4509-b38c-dd327728045c.png'
WHERE image_url LIKE '%/uploads/8f70f7ca-dcb1-4509-b38c-dd327728045c.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640113/Products/8f70f7ca-dcb1-4509-b38c-dd327728045c.png'
WHERE thumbnail_url LIKE '%/uploads/8f70f7ca-dcb1-4509-b38c-dd327728045c.png';

-- 91a2aa47-c3c6-491e-91bc-dad010bfcd45.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640119/Products/91a2aa47-c3c6-491e-91bc-dad010bfcd45.png'
WHERE image_url LIKE '%/uploads/91a2aa47-c3c6-491e-91bc-dad010bfcd45.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640119/Products/91a2aa47-c3c6-491e-91bc-dad010bfcd45.png'
WHERE thumbnail_url LIKE '%/uploads/91a2aa47-c3c6-491e-91bc-dad010bfcd45.png';

-- 947b9aff-c7e8-49b5-9894-b7906237b6d7.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640126/Products/947b9aff-c7e8-49b5-9894-b7906237b6d7.png'
WHERE image_url LIKE '%/uploads/947b9aff-c7e8-49b5-9894-b7906237b6d7.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640126/Products/947b9aff-c7e8-49b5-9894-b7906237b6d7.png'
WHERE thumbnail_url LIKE '%/uploads/947b9aff-c7e8-49b5-9894-b7906237b6d7.png';

-- 9b4e7100-2208-4adb-a474-6b27bc2a8be8.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640133/Products/9b4e7100-2208-4adb-a474-6b27bc2a8be8.png'
WHERE image_url LIKE '%/uploads/9b4e7100-2208-4adb-a474-6b27bc2a8be8.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640133/Products/9b4e7100-2208-4adb-a474-6b27bc2a8be8.png'
WHERE thumbnail_url LIKE '%/uploads/9b4e7100-2208-4adb-a474-6b27bc2a8be8.png';

-- a6b38874-2d70-4366-b5db-8a8bbe490c2e.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640141/Products/a6b38874-2d70-4366-b5db-8a8bbe490c2e.png'
WHERE image_url LIKE '%/uploads/a6b38874-2d70-4366-b5db-8a8bbe490c2e.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640141/Products/a6b38874-2d70-4366-b5db-8a8bbe490c2e.png'
WHERE thumbnail_url LIKE '%/uploads/a6b38874-2d70-4366-b5db-8a8bbe490c2e.png';

-- a91d0452-4f75-45c1-a36a-859bc012ac92.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640147/Products/a91d0452-4f75-45c1-a36a-859bc012ac92.png'
WHERE image_url LIKE '%/uploads/a91d0452-4f75-45c1-a36a-859bc012ac92.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640147/Products/a91d0452-4f75-45c1-a36a-859bc012ac92.png'
WHERE thumbnail_url LIKE '%/uploads/a91d0452-4f75-45c1-a36a-859bc012ac92.png';

-- a9ce492e-817e-489b-b968-a66e211630ce.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640153/Products/a9ce492e-817e-489b-b968-a66e211630ce.png'
WHERE image_url LIKE '%/uploads/a9ce492e-817e-489b-b968-a66e211630ce.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640153/Products/a9ce492e-817e-489b-b968-a66e211630ce.png'
WHERE thumbnail_url LIKE '%/uploads/a9ce492e-817e-489b-b968-a66e211630ce.png';

-- acd56093-1f2a-4796-bf5b-5cf307f4c28f.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640158/Products/acd56093-1f2a-4796-bf5b-5cf307f4c28f.png'
WHERE image_url LIKE '%/uploads/acd56093-1f2a-4796-bf5b-5cf307f4c28f.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640158/Products/acd56093-1f2a-4796-bf5b-5cf307f4c28f.png'
WHERE thumbnail_url LIKE '%/uploads/acd56093-1f2a-4796-bf5b-5cf307f4c28f.png';

-- af175198-e806-403d-bf77-93e628ecbdc3.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640164/Products/af175198-e806-403d-bf77-93e628ecbdc3.png'
WHERE image_url LIKE '%/uploads/af175198-e806-403d-bf77-93e628ecbdc3.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640164/Products/af175198-e806-403d-bf77-93e628ecbdc3.png'
WHERE thumbnail_url LIKE '%/uploads/af175198-e806-403d-bf77-93e628ecbdc3.png';

-- afcdefeb-9147-4755-abcc-7662acd72713.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640171/Products/afcdefeb-9147-4755-abcc-7662acd72713.png'
WHERE image_url LIKE '%/uploads/afcdefeb-9147-4755-abcc-7662acd72713.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640171/Products/afcdefeb-9147-4755-abcc-7662acd72713.png'
WHERE thumbnail_url LIKE '%/uploads/afcdefeb-9147-4755-abcc-7662acd72713.png';

-- b0f3a061-6122-42ae-bb13-553f3a5f04ce.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640178/Products/b0f3a061-6122-42ae-bb13-553f3a5f04ce.png'
WHERE image_url LIKE '%/uploads/b0f3a061-6122-42ae-bb13-553f3a5f04ce.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640178/Products/b0f3a061-6122-42ae-bb13-553f3a5f04ce.png'
WHERE thumbnail_url LIKE '%/uploads/b0f3a061-6122-42ae-bb13-553f3a5f04ce.png';

-- b2366fb1-cf89-40ac-ba0f-713c1ab5815e.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640186/Products/b2366fb1-cf89-40ac-ba0f-713c1ab5815e.png'
WHERE image_url LIKE '%/uploads/b2366fb1-cf89-40ac-ba0f-713c1ab5815e.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640186/Products/b2366fb1-cf89-40ac-ba0f-713c1ab5815e.png'
WHERE thumbnail_url LIKE '%/uploads/b2366fb1-cf89-40ac-ba0f-713c1ab5815e.png';

-- b70252bc-7c23-4d72-a6ec-ab734e9f6bb0.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640192/Products/b70252bc-7c23-4d72-a6ec-ab734e9f6bb0.png'
WHERE image_url LIKE '%/uploads/b70252bc-7c23-4d72-a6ec-ab734e9f6bb0.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640192/Products/b70252bc-7c23-4d72-a6ec-ab734e9f6bb0.png'
WHERE thumbnail_url LIKE '%/uploads/b70252bc-7c23-4d72-a6ec-ab734e9f6bb0.png';

-- b88ff579-436c-46a4-87a9-9b49b466c2a5.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640200/Products/b88ff579-436c-46a4-87a9-9b49b466c2a5.png'
WHERE image_url LIKE '%/uploads/b88ff579-436c-46a4-87a9-9b49b466c2a5.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640200/Products/b88ff579-436c-46a4-87a9-9b49b466c2a5.png'
WHERE thumbnail_url LIKE '%/uploads/b88ff579-436c-46a4-87a9-9b49b466c2a5.png';

-- b98c2f08-ad80-4b05-a166-c97dbfe20ca5.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640206/Products/b98c2f08-ad80-4b05-a166-c97dbfe20ca5.png'
WHERE image_url LIKE '%/uploads/b98c2f08-ad80-4b05-a166-c97dbfe20ca5.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640206/Products/b98c2f08-ad80-4b05-a166-c97dbfe20ca5.png'
WHERE thumbnail_url LIKE '%/uploads/b98c2f08-ad80-4b05-a166-c97dbfe20ca5.png';

-- be58c109-d1ff-4a2c-a7e3-6575b6cdfce0.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640213/Products/be58c109-d1ff-4a2c-a7e3-6575b6cdfce0.png'
WHERE image_url LIKE '%/uploads/be58c109-d1ff-4a2c-a7e3-6575b6cdfce0.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640213/Products/be58c109-d1ff-4a2c-a7e3-6575b6cdfce0.png'
WHERE thumbnail_url LIKE '%/uploads/be58c109-d1ff-4a2c-a7e3-6575b6cdfce0.png';

-- c846d975-55ed-49a4-8520-0c00b8b8cfe8.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640219/Products/c846d975-55ed-49a4-8520-0c00b8b8cfe8.png'
WHERE image_url LIKE '%/uploads/c846d975-55ed-49a4-8520-0c00b8b8cfe8.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640219/Products/c846d975-55ed-49a4-8520-0c00b8b8cfe8.png'
WHERE thumbnail_url LIKE '%/uploads/c846d975-55ed-49a4-8520-0c00b8b8cfe8.png';

-- cca5aee7-2c73-4534-9024-884be65b1af3.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640226/Products/cca5aee7-2c73-4534-9024-884be65b1af3.png'
WHERE image_url LIKE '%/uploads/cca5aee7-2c73-4534-9024-884be65b1af3.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640226/Products/cca5aee7-2c73-4534-9024-884be65b1af3.png'
WHERE thumbnail_url LIKE '%/uploads/cca5aee7-2c73-4534-9024-884be65b1af3.png';

-- d10f3415-5da2-45b2-bd4f-29950cf5c4b8.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640232/Products/d10f3415-5da2-45b2-bd4f-29950cf5c4b8.png'
WHERE image_url LIKE '%/uploads/d10f3415-5da2-45b2-bd4f-29950cf5c4b8.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640232/Products/d10f3415-5da2-45b2-bd4f-29950cf5c4b8.png'
WHERE thumbnail_url LIKE '%/uploads/d10f3415-5da2-45b2-bd4f-29950cf5c4b8.png';

-- d6e87189-60b0-48ba-8b0f-3469fbcfbcfc.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640239/Products/d6e87189-60b0-48ba-8b0f-3469fbcfbcfc.png'
WHERE image_url LIKE '%/uploads/d6e87189-60b0-48ba-8b0f-3469fbcfbcfc.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640239/Products/d6e87189-60b0-48ba-8b0f-3469fbcfbcfc.png'
WHERE thumbnail_url LIKE '%/uploads/d6e87189-60b0-48ba-8b0f-3469fbcfbcfc.png';

-- da2dbb78-e85d-4745-909c-0e4acb74c14d.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640246/Products/da2dbb78-e85d-4745-909c-0e4acb74c14d.png'
WHERE image_url LIKE '%/uploads/da2dbb78-e85d-4745-909c-0e4acb74c14d.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640246/Products/da2dbb78-e85d-4745-909c-0e4acb74c14d.png'
WHERE thumbnail_url LIKE '%/uploads/da2dbb78-e85d-4745-909c-0e4acb74c14d.png';

-- e0ef8448-a52f-4141-8a13-ea415035b9c1.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640253/Products/e0ef8448-a52f-4141-8a13-ea415035b9c1.png'
WHERE image_url LIKE '%/uploads/e0ef8448-a52f-4141-8a13-ea415035b9c1.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640253/Products/e0ef8448-a52f-4141-8a13-ea415035b9c1.png'
WHERE thumbnail_url LIKE '%/uploads/e0ef8448-a52f-4141-8a13-ea415035b9c1.png';

-- e1961401-6bca-4b3f-8606-9120a8c0b1f4.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640259/Products/e1961401-6bca-4b3f-8606-9120a8c0b1f4.png'
WHERE image_url LIKE '%/uploads/e1961401-6bca-4b3f-8606-9120a8c0b1f4.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640259/Products/e1961401-6bca-4b3f-8606-9120a8c0b1f4.png'
WHERE thumbnail_url LIKE '%/uploads/e1961401-6bca-4b3f-8606-9120a8c0b1f4.png';

-- e3f36440-176c-470c-9323-adc54dfe532d.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640265/Products/e3f36440-176c-470c-9323-adc54dfe532d.png'
WHERE image_url LIKE '%/uploads/e3f36440-176c-470c-9323-adc54dfe532d.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640265/Products/e3f36440-176c-470c-9323-adc54dfe532d.png'
WHERE thumbnail_url LIKE '%/uploads/e3f36440-176c-470c-9323-adc54dfe532d.png';

-- ecde6c84-86b2-4d53-a7de-e5ab53807922.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640271/Products/ecde6c84-86b2-4d53-a7de-e5ab53807922.png'
WHERE image_url LIKE '%/uploads/ecde6c84-86b2-4d53-a7de-e5ab53807922.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640271/Products/ecde6c84-86b2-4d53-a7de-e5ab53807922.png'
WHERE thumbnail_url LIKE '%/uploads/ecde6c84-86b2-4d53-a7de-e5ab53807922.png';

-- f54ca129-3333-4d51-9d39-523d90b1a4d7.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640278/Products/f54ca129-3333-4d51-9d39-523d90b1a4d7.png'
WHERE image_url LIKE '%/uploads/f54ca129-3333-4d51-9d39-523d90b1a4d7.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640278/Products/f54ca129-3333-4d51-9d39-523d90b1a4d7.png'
WHERE thumbnail_url LIKE '%/uploads/f54ca129-3333-4d51-9d39-523d90b1a4d7.png';

-- f81e7c93-6f9c-4c9a-a780-955dfc0583cb.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640286/Products/f81e7c93-6f9c-4c9a-a780-955dfc0583cb.png'
WHERE image_url LIKE '%/uploads/f81e7c93-6f9c-4c9a-a780-955dfc0583cb.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640286/Products/f81e7c93-6f9c-4c9a-a780-955dfc0583cb.png'
WHERE thumbnail_url LIKE '%/uploads/f81e7c93-6f9c-4c9a-a780-955dfc0583cb.png';

-- fab1ef77-87d8-42b8-a2fe-6018556ba714.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640293/Products/fab1ef77-87d8-42b8-a2fe-6018556ba714.png'
WHERE image_url LIKE '%/uploads/fab1ef77-87d8-42b8-a2fe-6018556ba714.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640293/Products/fab1ef77-87d8-42b8-a2fe-6018556ba714.png'
WHERE thumbnail_url LIKE '%/uploads/fab1ef77-87d8-42b8-a2fe-6018556ba714.png';

-- fe94c4f2-3280-49b2-96b0-d8750d02bc28.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640300/Products/fe94c4f2-3280-49b2-96b0-d8750d02bc28.png'
WHERE image_url LIKE '%/uploads/fe94c4f2-3280-49b2-96b0-d8750d02bc28.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640300/Products/fe94c4f2-3280-49b2-96b0-d8750d02bc28.png'
WHERE thumbnail_url LIKE '%/uploads/fe94c4f2-3280-49b2-96b0-d8750d02bc28.png';

-- ff383315-df4b-484b-a983-2fba83b89f09.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640306/Products/ff383315-df4b-484b-a983-2fba83b89f09.png'
WHERE image_url LIKE '%/uploads/ff383315-df4b-484b-a983-2fba83b89f09.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640306/Products/ff383315-df4b-484b-a983-2fba83b89f09.png'
WHERE thumbnail_url LIKE '%/uploads/ff383315-df4b-484b-a983-2fba83b89f09.png';

-- ff4e1825-1058-4b07-99e6-1edc50475490.png
UPDATE public.product_images
SET image_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640311/Products/ff4e1825-1058-4b07-99e6-1edc50475490.png'
WHERE image_url LIKE '%/uploads/ff4e1825-1058-4b07-99e6-1edc50475490.png';

UPDATE public.product_variants
SET thumbnail_url = 'https://res.cloudinary.com/product-aura/image/upload/v1782640311/Products/ff4e1825-1058-4b07-99e6-1edc50475490.png'
WHERE thumbnail_url LIKE '%/uploads/ff4e1825-1058-4b07-99e6-1edc50475490.png';

COMMIT;
