param(
    [string]$UploadDir = "",
    [string]$OutputSql = "",
    [string]$CloudinaryFolder = "",
    [int]$MaxRetries = 5
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $UploadDir) {
    $UploadDir = Join-Path $repoRoot "BE\uploads"
}
if (-not $OutputSql) {
    $OutputSql = Join-Path $PSScriptRoot "cloudinary-upload-updates.sql"
}
if (-not $CloudinaryFolder) {
    $CloudinaryFolder = if ($env:CLOUDINARY_FOLDER) { $env:CLOUDINARY_FOLDER } else { "Products" }
}

$cloudName = $env:CLOUDINARY_CLOUD_NAME
$apiKey = $env:CLOUDINARY_API_KEY
$apiSecret = $env:CLOUDINARY_API_SECRET

if ([string]::IsNullOrWhiteSpace($cloudName) -or [string]::IsNullOrWhiteSpace($apiKey) -or [string]::IsNullOrWhiteSpace($apiSecret)) {
    throw "Missing Cloudinary env vars. Set CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, and CLOUDINARY_API_SECRET first."
}

if (-not (Test-Path -LiteralPath $UploadDir)) {
    throw "Upload directory not found: $UploadDir"
}

$curl = Get-Command curl.exe -ErrorAction SilentlyContinue
if (-not $curl) {
    throw "curl.exe was not found. Please install curl or run this script on Windows 10/11 with curl available."
}

function Get-Sha1Hex {
    param([Parameter(Mandatory = $true)][string]$Value)

    $sha1 = [System.Security.Cryptography.SHA1]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
        $hash = $sha1.ComputeHash($bytes)
        return -join ($hash | ForEach-Object { $_.ToString("x2") })
    }
    finally {
        $sha1.Dispose()
    }
}

function Escape-Sql {
    param([Parameter(Mandatory = $true)][string]$Value)
    return $Value.Replace("'", "''")
}

function Upload-ImageToCloudinary {
    param(
        [Parameter(Mandatory = $true)][System.IO.FileInfo]$File,
        [Parameter(Mandatory = $true)][string]$PublicId
    )

    $timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $signaturePayload = "folder=$CloudinaryFolder&overwrite=true&public_id=$PublicId&timestamp=$timestamp$apiSecret"
    $signature = Get-Sha1Hex -Value $signaturePayload
    $url = "https://api.cloudinary.com/v1_1/$cloudName/image/upload"

    $args = @(
        "-sS",
        "--ipv4",
        "--connect-timeout", "30",
        "--max-time", "300",
        "-X", "POST",
        $url,
        "-F", "file=@$($File.FullName)",
        "-F", "api_key=$apiKey",
        "-F", "timestamp=$timestamp",
        "-F", "signature=$signature",
        "-F", "folder=$CloudinaryFolder",
        "-F", "overwrite=true",
        "-F", "public_id=$PublicId"
    )

    $body = $null
    for ($attempt = 1; $attempt -le $MaxRetries; $attempt++) {
        $body = & $curl.Source @args
        if ($LASTEXITCODE -eq 0) {
            break
        }

        if ($attempt -eq $MaxRetries) {
            throw "curl upload failed for $($File.Name) with exit code $LASTEXITCODE after $MaxRetries attempts"
        }

        $delaySeconds = [Math]::Min(20, 2 * $attempt)
        Write-Host "Upload failed for $($File.Name), retrying in $delaySeconds seconds... ($attempt/$MaxRetries)"
        Start-Sleep -Seconds $delaySeconds
    }

    try {
        $json = $body | ConvertFrom-Json
    }
    catch {
        throw "Cloudinary returned non-JSON response for $($File.Name): $body"
    }

    if ($json.error) {
        throw "Cloudinary upload failed for $($File.Name): $($json.error.message)"
    }

    if ([string]::IsNullOrWhiteSpace([string]$json.secure_url)) {
        throw "Cloudinary did not return secure_url for $($File.Name): $body"
    }

    return [string]$json.secure_url
}

$files = Get-ChildItem -LiteralPath $UploadDir -File |
    Where-Object { $_.Extension -match '^\.(png|jpg|jpeg|webp|gif)$' } |
    Sort-Object Name

if ($files.Count -eq 0) {
    throw "No image files found in: $UploadDir"
}

$sqlLines = New-Object System.Collections.Generic.List[string]
$sqlLines.Add("-- Generated by scripts/migrate-uploads-to-cloudinary.ps1")
$sqlLines.Add("-- Run this against the Railway PostgreSQL database after reviewing it.")
$sqlLines.Add("-- Source folder: $UploadDir")
$sqlLines.Add("-- Cloudinary folder: $CloudinaryFolder")
$sqlLines.Add("BEGIN;")

$index = 0
foreach ($file in $files) {
    $index++
    $publicId = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    Write-Host "[$index/$($files.Count)] Uploading $($file.Name) ..."

    $secureUrl = Upload-ImageToCloudinary -File $file -PublicId $publicId
    $escapedUrl = Escape-Sql -Value $secureUrl
    $escapedFile = Escape-Sql -Value $file.Name

    $sqlLines.Add("")
    $sqlLines.Add("-- $($file.Name)")
    $sqlLines.Add("UPDATE public.product_images")
    $sqlLines.Add("SET image_url = '$escapedUrl'")
    $sqlLines.Add("WHERE image_url LIKE '%/uploads/$escapedFile';")
    $sqlLines.Add("")
    $sqlLines.Add("UPDATE public.product_variants")
    $sqlLines.Add("SET thumbnail_url = '$escapedUrl'")
    $sqlLines.Add("WHERE thumbnail_url LIKE '%/uploads/$escapedFile';")

    Start-Sleep -Milliseconds 500
}

$sqlLines.Add("")
$sqlLines.Add("COMMIT;")

Set-Content -LiteralPath $OutputSql -Value $sqlLines -Encoding UTF8
Write-Host "Done. SQL written to: $OutputSql"
